'use client';

import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Typography from '@tiptap/extension-typography';
import { Table } from '@tiptap/extension-table';
import { TableRow } from '@tiptap/extension-table-row';
import { TableCell } from '@tiptap/extension-table-cell';
import { TableHeader } from '@tiptap/extension-table-header';
import { Markdown } from 'tiptap-markdown';
import { useEffect } from 'react';
import './tiptap-editor.css';

interface SrsDocumentProps {
    content: string | undefined | null;
    title?: string;
    documentType?: string;
    version?: string;
    status?: string;
    date?: string;
    targetAudience?: string;
    preparedBy?: string;
    standard?: string;
}

export default function SrsDocument({
    content,
    title = 'Untitled Project',
    documentType = 'Software Requirements Specification (SRS)',
    version = '1.0',
    status = 'Draft',
    date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
    targetAudience = 'Stakeholders',
    preparedBy = 'Generated by PRD Studio',
    standard = 'IEEE Std 830-1998'
}: SrsDocumentProps) {

    // ── Tiptap read-only editor ──────────────────────────────────────────────
    const editor = useEditor({
        extensions: [
            StarterKit,
            Typography,
            Table.configure({ resizable: false }),
            TableRow,
            TableHeader,
            TableCell,
            Markdown.configure({
                html: false,
                transformCopiedText: true,
                transformPastedText: true,
            }),
        ],
        content: content || '',
        editable: false,
        immediatelyRender: false,
        editorProps: {
            attributes: { class: 'tiptap-editor-content focus:outline-none' },
        },
    });

    // Re-sync when content prop changes (e.g. new generation)
    useEffect(() => {
        if (editor && content) {
            editor.commands.setContent(content);
        }
    }, [content, editor]);

    // ── Table of Contents (parsed from markdown headings) ────────────────────
    type TocEntry = { level: number; text: string; index: string };
    const tocEntries: TocEntry[] = [];
    let h1Count = 0;
    let h2Count = 0;
    for (const line of (content ?? '').split('\n')) {
        const h2Match = line.match(/^##\s+(.+)/);
        const h1Match = line.match(/^#\s+(.+)/);
        if (h2Match) {
            h2Count++;
            tocEntries.push({ level: 2, text: h2Match[1].trim(), index: `${h1Count}.${h2Count}` });
        } else if (h1Match) {
            h1Count++;
            h2Count = 0;
            tocEntries.push({ level: 1, text: h1Match[1].trim(), index: `${h1Count}.` });
        }
    }

    if (!content) return null;

    return (
        <div className="bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 font-sans max-w-[900px] mx-auto shadow-2xl overflow-hidden min-h-[1100px] flex flex-col border border-slate-200 dark:border-slate-800">

            {/* ── Header ── */}
            <header className="px-12 py-8 flex justify-between items-center text-[11px] font-bold tracking-[0.2em] text-slate-400 dark:text-slate-500 uppercase border-b border-slate-200 dark:border-slate-800">
                <span>PRD STUDIO</span>
                <span className="text-slate-500 dark:text-slate-400">CONFIDENTIAL DRAFT</span>
            </header>

            <div className="flex-1 px-10 md:px-16 py-8">

                {/* ── Document Title ── */}
                <div className="mb-10">
                    <h2 className="text-[10px] font-bold tracking-[0.2em] text-slate-500 dark:text-slate-400 uppercase mb-2">
                        {documentType.replace(/\s*\(.*\)$/g, '')}
                    </h2>
                    <p className="text-3xl md:text-4xl font-black text-slate-900 dark:text-white tracking-tight capitalize leading-tight">
                        {title}
                    </p>
                </div>

                {/* ── Metadata Table ── */}
                <div className="mb-10 border-t border-slate-100 dark:border-slate-800 font-medium">
                    <table className="w-full text-xs border-collapse">
                        <tbody>
                            {[
                                { label: 'Document Type', value: documentType },
                                { label: 'Version',       value: version },
                                { label: 'Status',        value: status },
                                { label: 'Date',          value: date },
                                { label: 'Target Audience', value: targetAudience },
                                { label: 'Prepared By',   value: preparedBy },
                                { label: 'Standard',      value: standard },
                            ].map((row, i) => (
                                <tr key={i} className="border-b border-slate-100 dark:border-slate-800 transition-colors hover:bg-slate-50/50 dark:hover:bg-slate-800/50">
                                    <td className="py-2.5 w-1/3 text-slate-400 dark:text-slate-500 uppercase tracking-wider text-[10px]">{row.label}</td>
                                    <td className="py-2.5 text-slate-700 dark:text-slate-300 font-bold">{row.value}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                <div className="mb-10 text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed max-w-xl italic">
                    <span className="font-bold uppercase tracking-wider not-italic">Note:</span>{' '}
                    A Software Requirements Specification (SRS) is a comprehensive description of the intended purpose
                    and environment for software under development, defining functional and non-functional requirements.
                </div>

                {/* ── Separator ── */}
                <div className="h-px w-full bg-black dark:bg-slate-300 mb-10" />

                {/* ── Table of Contents ── */}
                {tocEntries.length > 0 && (
                    <div className="mb-12">
                        <h3 className="text-[10px] font-bold tracking-[0.2em] text-slate-600 dark:text-slate-400 uppercase mb-6">
                            TABLE OF CONTENTS
                        </h3>
                        <div className="space-y-1.5 text-sm">
                            {tocEntries.map((entry, i) => (
                                <div
                                    key={i}
                                    className={`flex items-end gap-2 group cursor-default ${entry.level === 2 ? 'pl-6 font-medium' : 'font-semibold'}`}
                                >
                                    <span className={`shrink-0 ${entry.level === 1 ? 'text-slate-500 dark:text-slate-400' : 'text-slate-400 dark:text-slate-500'}`}>
                                        {entry.index}
                                    </span>
                                    <span className={`${
                                        entry.level === 1
                                            ? 'text-slate-700 dark:text-slate-200 group-hover:text-slate-900 dark:group-hover:text-white'
                                            : 'text-slate-600 dark:text-slate-300 group-hover:text-slate-800 dark:group-hover:text-slate-100'
                                    } transition-colors`}>
                                        {entry.text}
                                    </span>
                                    <div className="flex-1 border-b border-dotted border-slate-200 dark:border-slate-800 mb-1.5 opacity-50" />
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* ── Tiptap read-only content ── */}
                <EditorContent editor={editor} />

            </div>

            {/* ── Footer ── */}
            <footer className="px-12 py-10 flex justify-between items-center text-[10px] font-bold uppercase tracking-widest text-slate-400 dark:text-slate-500 border-t border-slate-100 dark:border-slate-800 bg-slate-50/30 dark:bg-slate-900/30">
                <div className="flex items-center gap-3">
                    <span>Generated by AI-PRD Studio</span>
                    <span className="text-slate-200 dark:text-slate-700">•</span>
                    <span>{standard}</span>
                </div>
                <div>{date}</div>
            </footer>
        </div>
    );
}